version: '3'
services:
  recommend:
    container_name: recommend
    build: .
    command: gunicorn -b :8000 manage:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env